// <auto-generated />
using System;
using HorseRacing.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorseRacing.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260611024654_UpdateTournamentRacingEntities")]
    partial class UpdateTournamentRacingEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorseRacing.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@gmail.com",
                            FullName = "Admin",
                            PasswordHash = "AQAAAAIAAYagAAAAEOCrttfaCVXXKv/Wy+gaYr7tVyJOwyV+HSs32fMKAssoSs0sVJHPz/k+M+vWi3bKQQ==",
                            RoleId = 1,
                            Status = "Active",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "owner@gmail.com",
                            FullName = "HorseOwner",
                            PasswordHash = "AQAAAAIAAYagAAAAEHwZ6VVoS037mIguxw+jqz7ak90xeEVNXLgyh4UPKuJyhPLZptFsDBXqipJGT6gLOw==",
                            RoleId = 2,
                            Status = "Active",
                            Username = "owner"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jockey@gmail.com",
                            FullName = "Jockey",
                            PasswordHash = "AQAAAAIAAYagAAAAEGghxh7vAiSQ5BaGlvd975fc4KUzEYzwSkskU45lcryGMmmSQ+tiPQMMJ/lvm769yw==",
                            RoleId = 3,
                            Status = "Active",
                            Username = "jockey"
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "referee@gmail.com",
                            FullName = "Referee",
                            PasswordHash = "AQAAAAIAAYagAAAAEKpXVcz+pbPeqnCDD6zooCAAG41O/p0QbcisCuTVKBY3NuuKEbxrFad4Wf+2tURsMw==",
                            RoleId = 4,
                            Status = "Active",
                            Username = "referee"
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "spectator@gmail.com",
                            FullName = "Spectator",
                            PasswordHash = "AQAAAAIAAYagAAAAEI7KFJe27AeVB7P+vqMsLmvFp3PBKSTno9RVSx+LT3nytSCHRFwDx8fvBP06Rx6liA==",
                            RoleId = 5,
                            Status = "Active",
                            Username = "spectator"
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<decimal>("Odds")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("RaceId");

                    b.HasIndex("UserId");

                    b.ToTable("Bets");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Breed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Horses");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.Property<int>("JockeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JockeyId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("RankingPoint")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JockeyId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("JockeyProfiles");

                    b.HasData(
                        new
                        {
                            JockeyId = 1,
                            ExperienceYears = 3,
                            RankingPoint = 100,
                            Status = "Active",
                            UserId = 3
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Payout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BetId");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prediction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PredictedWinner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Predictions");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("JockeyPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OwnerPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Prizes");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorseId")
                        .HasColumnType("int");

                    b.Property<int>("JockeyId")
                        .HasColumnType("int");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HorseId");

                    b.HasIndex("JockeyId");

                    b.HasIndex("RaceId");

                    b.ToTable("RaceEntries");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Winner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RaceResults");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceViolation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Penalty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeProfile", b =>
                {
                    b.Property<int>("RefereeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefereeId"));

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RefereeId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("RefereeProfiles");

                    b.HasData(
                        new
                        {
                            RefereeId = 1,
                            ExperienceYears = 5,
                            LicenseNumber = "LIC-REF-001",
                            Status = "Active",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "HorseOwner"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Jockey"
                        },
                        new
                        {
                            RoleId = 4,
                            Name = "Referee"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Spectator"
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.TournamentPrizePayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("UserId");

                    b.ToTable("TournamentPrizePayouts");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.Property<long>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RaceId"));

                    b.Property<int>("DistanceMeter")
                        .HasColumnType("int");

                    b.Property<int>("MaxLanes")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RaceDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("RoundId")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaceId");

                    b.HasIndex("RoundId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.RaceRefereeAssignment", b =>
                {
                    b.Property<long>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AssignmentId"));

                    b.Property<DateTime?>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<long>("RaceId")
                        .HasColumnType("bigint");

                    b.Property<int>("RefereeId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AssignmentId");

                    b.HasIndex("RaceId");

                    b.HasIndex("RefereeId");

                    b.ToTable("RaceRefereeAssignments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.Property<long>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RoundId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TournamentId")
                        .HasColumnType("bigint");

                    b.HasKey("RoundId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Tournament", b =>
                {
                    b.Property<long>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TournamentId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("WalletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WalletId"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WalletId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            WalletId = 1,
                            Balance = 0m,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Bet", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Race");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Horse", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.JockeyProfile", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.JockeyProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Notification", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Payout", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Bet", "Bet")
                        .WithMany()
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bet");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Prize", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceEntry", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Horse", "Horse")
                        .WithMany()
                        .HasForeignKey("HorseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "Jockey")
                        .WithMany()
                        .HasForeignKey("JockeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Horse");

                    b.Navigation("Jockey");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RaceViolation", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Race");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.RefereeProfile", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.RefereeProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.TournamentPrizePayout", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Round", "Round")
                        .WithMany("Races")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.RaceRefereeAssignment", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Race", "Race")
                        .WithMany("RaceRefereeAssignments")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorseRacing.Domain.Entities.RefereeProfile", "RefereeProfile")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Race");

                    b.Navigation("RefereeProfile");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Tournaments.Tournament", "Tournament")
                        .WithMany("Rounds")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.AppUser", "User")
                        .WithOne()
                        .HasForeignKey("HorseRacing.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.WalletTransaction", b =>
                {
                    b.HasOne("HorseRacing.Domain.Entities.Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Race", b =>
                {
                    b.Navigation("RaceRefereeAssignments");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Round", b =>
                {
                    b.Navigation("Races");
                });

            modelBuilder.Entity("HorseRacing.Domain.Entities.Tournaments.Tournament", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
